cp six-mohex-1.sgf    gm01.sgf
cp six-mohex-3.sgf    gm13.sgf
cp mohex-six-2.sgf    gm02.sgf
cp mohex-six-4.sgf    gm14.sgf
cp wolve-yopt-1.sgf   gm03.sgf
cp wolve-yopt-3.sgf   gm15.sgf
cp yopt-wolve-2.sgf   gm04.sgf
cp yopt-wolve-4.sgf   gm16.sgf
cp wolve-six-1.sgf    gm05.sgf
cp wolve-six-3.sgf    gm17.sgf
cp six-wolve-2.sgf    gm06.sgf
cp six-wolve-4.sgf    gm18.sgf
cp mohex-yopt-1.sgf   gm07.sgf
cp mohex-yopt-3.sgf   gm19.sgf
cp yopt-mohex-2.sgf   gm08.sgf
cp yopt-mohex-4.sgf   gm20.sgf
cp six-yopt-1.sgf     gm09.sgf
cp six-yopt-3.sgf     gm21.sgf
cp yopt-six-2.sgf     gm10.sgf
cp yopt-six-4.sgf     gm22.sgf
cp mohex-wolve-1.sgf  gm11.sgf
cp mohex-wolve-3.sgf  gm23.sgf
cp wolve-mohex-2.sgf  gm12.sgf
cp wolve-mohex-4.sgf  gm24.sgf
