../../trans/sgf2txt < games/sgf/gm01* | ../../trans/txt2p | ../../trans/p2hd > games/hexdiag/gm01.hexdiag
../../trans/sgf2txt < games/sgf/gm02* | ../../trans/txt2p | ../../trans/p2hd > games/hexdiag/gm02.hexdiag
../../trans/sgf2txt < games/sgf/gm03* | ../../trans/txt2p | ../../trans/p2hd > games/hexdiag/gm03.hexdiag
../../trans/sgf2txt < games/sgf/gm04* | ../../trans/txt2p | ../../trans/p2hd > games/hexdiag/gm04.hexdiag
../../trans/sgf2txt < games/sgf/gm05* | ../../trans/txt2p | ../../trans/p2hd > games/hexdiag/gm05.hexdiag
../../trans/sgf2txt < games/sgf/gm06* | ../../trans/txt2p | ../../trans/p2hd > games/hexdiag/gm06.hexdiag
../../trans/sgf2txt < games/sgf/gm07* | ../../trans/txt2p | ../../trans/p2hd > games/hexdiag/gm07.hexdiag
../../trans/sgf2txt < games/sgf/gm08* | ../../trans/txt2p | ../../trans/p2hd > games/hexdiag/gm08.hexdiag
../../trans/sgf2txt < games/sgf/gm09* | ../../trans/txt2p | ../../trans/p2hd > games/hexdiag/gm09.hexdiag
../../trans/sgf2txt < games/sgf/gm10* | ../../trans/txt2p | ../../trans/p2hd > games/hexdiag/gm10.hexdiag
../../trans/sgf2txt < games/sgf/gm11* | ../../trans/txt2p | ../../trans/p2hd > games/hexdiag/gm11.hexdiag
../../trans/sgf2txt < games/sgf/gm12* | ../../trans/txt2p | ../../trans/p2hd > games/hexdiag/gm12.hexdiag
